INSERT INTO `direccion` (`direccion`,`ciudad`,`provincia`,`pais`)
VALUES
  ("Ap #806-2986 Sed Rd.","Palma de Mallorca","Västra Götalands län","Poland"),
  ("Ap #323-5558 Class Rd.","Sagamu","Bremen","Italy"),
  ("Ap #306-2502 Orci Avenue","Ternopil","Ogun","Chile"),
  ("6475 Proin Rd.","Beijing","British Columbia","Brazil"),
  ("8304 Sodales Rd.","Cusco","Noord Holland","Vietnam"),
  ("102-3064 Ligula. St.","Taltal","Östergötlands län","Spain"),
  ("Ap #726-3317 Ut St.","Gia Bình","Ulster","United States"),
  ("3396 Nibh Avenue","Peine","Maranhão","Indonesia"),
  ("601-1945 Consectetuer, Road","Kon Tum","Novosibirsk Oblast","Philippines"),
  ("457-5755 Dignissim Avenue","Eckville","Los Lagos","Indonesia"),
  ("P.O. Box 114, 2221 Ante Avenue","Da Lat","Paraíba","Ukraine"),
  ("7264 Dui Rd.","Cork","Zhōngnán","Italy"),
  ("8058 Diam. Av.","Mexicali","Arequipa","Ireland"),
  ("821-2799 Eget Ave","Horten","Osun","Netherlands"),
  ("2669 Lectus Avenue","Port Nolloth","Franche-Comté","Russian Federation"),
  ("Ap #921-5394 Adipiscing Rd.","Schleswig","Sicilia","Chile"),
  ("Ap #389-4572 Sollicitudin Ave","Cork","Mexico City","Spain"),
  ("P.O. Box 328, 4623 Quis, Rd.","Tame","Hưng Yên","Mexico"),
  ("287-3889 Phasellus Rd.","Sierning","Puntarenas","Chile"),
  ("Ap #433-739 Arcu. Road","Seogwipo","Kharkiv oblast","India"),
  ("P.O. Box 459, 9916 Nonummy St.","OugrŽe","Mersin","Chile"),
  ("6871 Proin Rd.","Tarma","Västra Götalands län","Spain"),
  ("9104 Suspendisse Ave","Belfast","Heredia","Vietnam"),
  ("Ap #762-3438 Ipsum. St.","Tollembeek","North Island","China"),
  ("Ap #261-7650 Nullam Av.","Barranca","Aydın","Turkey"),
  ("764-4042 Egestas Av.","Oryol","San José","Nigeria"),
  ("Ap #493-8921 Dignissim Street","Minitonas","Huáběi","Indonesia"),
  ("172-3830 Tristique St.","Bojano","Cundinamarca","Germany"),
  ("886-7705 Orci St.","Zhejiang","Oost-Vlaanderen","Canada"),
  ("569-6339 Ornare. Av.","Reading","Podlaskie","Australia"),
  ("P.O. Box 696, 4679 Donec Street","Calarcá","Nariño","Germany"),
  ("Ap #351-8436 Vestibulum Road","Enns","Guanacaste","Poland"),
  ("957-4705 Fusce St.","Ludlow","Tambov Oblast","Brazil"),
  ("640-2199 Faucibus Rd.","Tielrode","Vlaams-Brabant","Brazil"),
  ("6829 Eu Road","Hamburg","Niger","Pakistan"),
  ("Ap #130-3524 Ac St.","Istanbul","Australian Capital Territory","Sweden"),
  ("5155 Id Street","Belfast","Dnipropetrovsk oblast","Ireland"),
  ("P.O. Box 449, 965 Tempus Ave","Court-Saint-Etienne","Veneto","Austria"),
  ("191-5698 Ut Rd.","Punta Arenas","Herefordshire","India"),
  ("781-3432 Purus, Avenue","Avesta","Gelderland","France"),
  ("P.O. Box 871, 7735 Dictum Ave","Ronciglione","Santa Catarina","India"),
  ("Ap #837-4321 Quam St.","Litueche","Castilla - La Mancha","Mexico"),
  ("P.O. Box 329, 3163 Nullam Av.","Hamburg","Jeju","Sweden"),
  ("172-4887 Velit Avenue","Bragança","North Island","Pakistan"),
  ("Ap #368-4137 Enim. St.","Kurgan","Hatay","Netherlands"),
  ("602-5752 Nec, Road","Delhi","Gilgit Baltistan","Nigeria"),
  ("Ap #994-6301 Nullam St.","Oudenburg","Hampshire","Canada"),
  ("7954 Ut Av.","Grey County","Overijssel","Belgium"),
  ("Ap #879-4720 Quisque St.","Sudbury","Samsun","United States"),
  ("274-5196 Tellus, Ave","Galway","Riau Islands","Colombia");
INSERT INTO `direccion` (`direccion`,`ciudad`,`provincia`,`pais`)
VALUES
  ("406-1008 Sapien. Avenue","Ludwigshafen","North Chungcheong","Chile"),
  ("896 Amet, Road","Villahermosa","Namen","Sweden"),
  ("Ap #140-3566 Sit St.","Rustenburg","South Australia","Italy"),
  ("P.O. Box 584, 537 Pellentesque Av.","Machilipatnam","San Andrés y Providencia","Costa Rica"),
  ("Ap #870-4207 Praesent St.","San Rafael","Sachsen-Anhalt","Colombia"),
  ("268-8183 Nunc Road","Baracaldo","Assam","China"),
  ("635-6830 Pellentesque Road","Hòa Bình","Valparaíso","Italy"),
  ("Ap #542-9117 Nonummy Street","Motala","Tamaulipas","Austria"),
  ("P.O. Box 508, 7693 Ut St.","Mohmand Agency","National Capital Region","Philippines"),
  ("994-393 Commodo Av.","Bedok","Castilla - La Mancha","Indonesia"),
  ("6853 Commodo Rd.","Criciúma","Munster","China"),
  ("Ap #694-5209 Phasellus Avenue","Marystown","Lower Austria","Poland"),
  ("8130 Ut Avenue","Altach","Valle d'Aosta","Belgium"),
  ("P.O. Box 965, 634 Vehicula Av.","Ceuta","Lakshadweep","New Zealand"),
  ("213-1149 Risus. St.","Liaoning","Antwerpen","Pakistan"),
  ("933-3103 Arcu St.","Floridablanca","Herefordshire","Peru"),
  ("Ap #801-1232 Mauris, Avenue","Delhi","Troms og Finnmark","Turkey"),
  ("Ap #884-9138 Pellentesque Road","Ziarat","Lower Austria","Chile"),
  ("P.O. Box 429, 5979 Vulputate, Rd.","Sudhanoti","Abruzzo","Pakistan"),
  ("3937 Aliquam Ave","Uijeongbu","Kaluga Oblast","Costa Rica"),
  ("257-7216 Ac Av.","Le Havre","Luxemburg","Nigeria"),
  ("P.O. Box 158, 985 Nec, Rd.","La Dorada","Dalarnas län","Russian Federation"),
  ("8860 Gravida. Ave","Canberra","Jeju","Norway"),
  ("Ap #109-967 Nibh St.","Brin-Navolok","Zuid Holland","Italy"),
  ("851-3743 Id, St.","Boise","Kentucky","France"),
  ("231-2257 Sed St.","Cuenca","Nordland","Vietnam"),
  ("853-2701 At Street","Zamora de Hidalgo","Zamboanga Peninsula","United States"),
  ("Ap #540-1714 Donec St.","Dos Hermanas","Vinnytsia oblast","Russian Federation"),
  ("Ap #934-7849 Nibh Av.","Calder","Munster","Singapore"),
  ("861-9581 Vel, Avenue","Odendaalsrus","South Australia","Sweden"),
  ("P.O. Box 465, 7208 Lorem, St.","Qinghai","Vienna","Ukraine"),
  ("P.O. Box 249, 2952 Hendrerit St.","Halesowen","Pernambuco","Spain"),
  ("299-6646 Pharetra Rd.","Cherepovets","New South Wales","Netherlands"),
  ("6596 Magna. St.","Daly","New South Wales","Nigeria"),
  ("Ap #659-1233 Ullamcorper Road","Motala","Limburg","Vietnam"),
  ("6564 Sed, Rd.","Goslar","Xīběi","Nigeria"),
  ("9620 Vestibulum Road","La Dorada","Gävleborgs län","Ireland"),
  ("P.O. Box 829, 5415 A, Avenue","Ceuta","Nord-Pas-de-Calais","Poland"),
  ("Ap #432-7146 Lorem St.","Paris","Pernambuco","Austria"),
  ("6710 Natoque St.","Cajamarca","Wielkopolskie","New Zealand"),
  ("181-4953 Sed Avenue","Narowal","Pennsylvania","Ukraine"),
  ("Ap #900-6238 Sodales St.","Toruń","Querétaro","Mexico"),
  ("P.O. Box 360, 8089 Est Ave","Billings","Gävleborgs län","Canada"),
  ("Ap #480-8017 Nonummy Ave","Magangué","Limón","Australia"),
  ("P.O. Box 904, 6844 Vehicula Rd.","Annan","Manipur","Poland"),
  ("Ap #731-7506 Vel, Rd.","Okene","Meghalaya","India"),
  ("Ap #724-5168 Rhoncus. Rd.","Orizaba","Bremen","Peru"),
  ("Ap #406-695 Diam Ave","Palencia","North Sulawesi","France"),
  ("980-3814 In Av.","Leeuwarden","Santa Catarina","Pakistan"),
  ("P.O. Box 142, 1715 Eget Avenue","Billings","Kocaeli","Chile");
INSERT INTO `direccion` (`direccion`,`ciudad`,`provincia`,`pais`)
VALUES
  ("P.O. Box 365, 8647 At St.","Sterling Heights","Mersin","Belgium"),
  ("586-8570 A, Ave","Frutillar","Maranhão","United Kingdom"),
  ("Ap #438-3596 Iaculis Ave","Victor Harbor","Kirovohrad oblast","Italy"),
  ("Ap #288-5760 Risus. Street","Los Mochis","Carinthia","United Kingdom"),
  ("894-7594 Vel St.","Sogamoso","Azad Kashmir","Vietnam"),
  ("826-3503 Diam Av.","Grave","Vorarlberg","Russian Federation"),
  ("Ap #710-1834 Etiam Avenue","Tuscaloosa","Connacht","Norway"),
  ("Ap #122-1015 Mi Av.","Mohmand Agency","New South Wales","Singapore"),
  ("P.O. Box 227, 3947 Enim. St.","Isabela City","Goa","Colombia"),
  ("P.O. Box 454, 1705 Tristique St.","Jecheon","Leinster","Sweden"),
  ("P.O. Box 886, 7481 Cursus. Ave","Belfast","Mersin","Germany"),
  ("2287 Non, Rd.","Tharparkar","Podkarpackie","New Zealand"),
  ("5515 Hymenaeos. Ave","Falun","Friesland","Norway"),
  ("720-9232 Nonummy St.","Francavilla Fontana","Loreto","Singapore"),
  ("840-1069 Arcu. Avenue","Palencia","Lagos","Peru"),
  ("469-692 Sit Av.","Bedok","Noord Holland","Colombia"),
  ("3375 Egestas. Av.","Thionville","Saskatchewan","South Korea"),
  ("P.O. Box 230, 1608 Nec, Av.","Galway","Luik","Spain"),
  ("P.O. Box 200, 2328 Sem. St.","Kemerovo","Hawaii","Australia"),
  ("423-8536 Turpis Avenue","Nicoya","Dorset","Australia"),
  ("4514 Sed St.","Juiz de Fora","Ontario","Pakistan"),
  ("334-7515 Sem St.","Poza Rica","Biobío","New Zealand"),
  ("Ap #769-3031 Blandit. St.","Bischofshofen","Puno","New Zealand"),
  ("382-2249 Hendrerit St.","Hainan","Cauca","United Kingdom"),
  ("794-2212 Felis, Avenue","Pekanbaru","Östergötlands län","Ukraine"),
  ("P.O. Box 527, 4807 Quam. Avenue","Arequipa","Quảng Bình","Belgium"),
  ("Ap #256-6723 Cum Rd.","Otegem","East Kalimantan","Pakistan"),
  ("Ap #961-2996 Lobortis Rd.","Leonding","Cordillera Administrative Region","Turkey"),
  ("Ap #593-4831 Nisl Avenue","St. Veit an der Glan","Tyrol","United States"),
  ("408-6033 Ullamcorper, Rd.","Río Bueno","Chelyabinsk Oblast","India"),
  ("Ap #886-5593 Gravida Road","Arequipa","Smolensk Oblast","Belgium"),
  ("352-3439 Cras St.","Liberia","North Region","Peru"),
  ("Ap #823-1394 Ornare, St.","Port Nolloth","Ohio","India"),
  ("P.O. Box 480, 8648 Sed Ave","Lim Chu Kang","Southwestern Tagalog Region","Austria"),
  ("862 Semper. Rd.","Seshego","Andhra Pradesh","Russian Federation"),
  ("Ap #718-7339 Nulla Road","Borlänge","Idaho","Philippines"),
  ("Ap #169-7952 Nunc. Avenue","Atlanta","Kujawsko-pomorskie","New Zealand"),
  ("Ap #278-3774 Aliquet Avenue","Fort Providence","Querétaro","South Africa"),
  ("505-6658 Rutrum St.","Nieuwegein","Imo","Belgium"),
  ("257-2536 Pharetra. Av.","Sikar","Denbighshire","Canada"),
  ("2773 Ad Road","Camborne","Rheinland-Pfalz","South Africa"),
  ("660-3024 Vitae, St.","Oamaru","Antofagasta","India"),
  ("1993 Dolor St.","Magadan","Delta","Philippines"),
  ("Ap #191-4672 Est Rd.","Vejano","Banten","Italy"),
  ("Ap #795-1780 Dui Rd.","San Rafael","Nordrhein-Westphalen","Peru"),
  ("Ap #665-1940 Etiam Avenue","Hall in Tirol","Murcia","Norway"),
  ("770-5949 Sed, St.","Floridablanca","Vinnytsia oblast","Costa Rica"),
  ("1794 Lorem St.","Calapan","Texas","Turkey"),
  ("P.O. Box 490, 1630 Lectus Ave","Balikpapan","Maryland","Austria"),
  ("699-8899 Elit. Rd.","Kamianets-Podilskyi","Kon Tum","Costa Rica");
INSERT INTO `direccion` (`direccion`,`ciudad`,`provincia`,`pais`)
VALUES
  ("Ap #184-6880 Ipsum St.","Zhytomyr","Michoacán","Brazil"),
  ("Ap #336-9067 Amet, St.","Buôn Ma Thuột","Quebec","New Zealand"),
  ("P.O. Box 521, 3258 Id Ave","Vänersborg","Cundinamarca","Colombia"),
  ("4048 Iaculis Road","Tuyên Quang","Puntarenas","Nigeria"),
  ("791-8392 Et Ave","Cartagena","Vorarlberg","Brazil"),
  ("P.O. Box 419, 6615 Auctor Av.","Patos","Arkhangelsk Oblast","Colombia"),
  ("Ap #396-2524 Neque. Ave","San Marcos","Manitoba","United Kingdom"),
  ("565-7964 Sit Road","Kent","Ontario","Costa Rica"),
  ("Ap #130-9274 Neque Rd.","Petrolina","Maule","Ireland"),
  ("Ap #212-7639 Semper Rd.","Darwin","Hertfordshire","Russian Federation"),
  ("Ap #199-8060 Egestas Av.","Stalowa Wola","Limburg","Netherlands"),
  ("P.O. Box 768, 7974 Aliquet Rd.","Mmabatho","Quebec","Ukraine"),
  ("Ap #752-5167 Nulla Rd.","Langenhagen","San Andrés y Providencia","Sweden"),
  ("589-4414 Eros Av.","Quinchao","Luhansk oblast","Poland"),
  ("982 Mauris Ave","Guangxi","Free State","Sweden"),
  ("704-1500 Ullamcorper. Rd.","Riksingen","Jigawa","Germany"),
  ("Ap #877-3488 Faucibus Street","Whakatane","Galicia","Ireland"),
  ("692-3223 Magna. Ave","Höchst","Rio Grande do Sul","Russian Federation"),
  ("P.O. Box 901, 4897 Sit St.","Trollhättan","Cajamarca","Spain"),
  ("P.O. Box 661, 1066 Proin St.","Ikot Ekpene","Balıkesir","Pakistan"),
  ("Ap #453-8905 Nec, St.","Odda","Yên Bái","United States"),
  ("Ap #471-8859 Sed Av.","Hilversum","Papua","Ireland"),
  ("370-4891 Ac Road","Santa Maria a Monte","Kahramanmaraş","Sweden"),
  ("689-3628 Placerat, Av.","Gijón","South Island","France"),
  ("Ap #834-2963 Vitae, Rd.","Tando Muhammad Khan","Centre","Norway"),
  ("Ap #873-9358 Sagittis Avenue","Płock","Loreto","Ireland"),
  ("154-7107 Vel, Rd.","Gwangyang","Melilla","Ireland"),
  ("792-958 Velit. Rd.","Villavicencio","Stockholms län","Ukraine"),
  ("3735 Ligula St.","São Luís","Minas Gerais","Costa Rica"),
  ("Ap #776-7777 Sagittis Rd.","Chernihiv","Mecklenburg-Vorpommern","Costa Rica"),
  ("Ap #487-6282 Suspendisse St.","Ergani","Bauchi","Germany"),
  ("489-6788 Hendrerit. Av.","Cleveland","Queensland","Netherlands"),
  ("635-3141 Odio Road","Jiutepec","Nordland","Chile"),
  ("368-5348 Mauris, Av.","Bukit Merah","Eastern Visayas","South Africa"),
  ("P.O. Box 900, 1495 Feugiat Road","Blenheim","Oryol Oblast","Brazil"),
  ("8137 Et Rd.","Cork","Connacht","France"),
  ("483-1829 Proin St.","Jecheon","Illes Balears","Chile"),
  ("Ap #157-9172 Sagittis St.","Kirov","Sindh","Chile"),
  ("P.O. Box 334, 7647 Ultrices Av.","Charlottetown","Junín","Ukraine"),
  ("301-5041 Aliquam Avenue","Badajoz","South Island","Turkey"),
  ("P.O. Box 698, 8149 Mauris Rd.","Zamora de Hidalgo","La Libertad","Norway"),
  ("Ap #148-8129 Fames Avenue","Puntarenas","Đồng Tháp","United Kingdom"),
  ("Ap #298-5796 Penatibus St.","Lampernisse","Nordland","Nigeria"),
  ("Ap #558-2528 Aliquet. Rd.","Enns","Principado de Asturias","Turkey"),
  ("6942 Et Rd.","Vienna","Limón","Nigeria"),
  ("Ap #272-9691 Donec Av.","Launceston","Lincolnshire","India"),
  ("296-1713 Magna Street","Chelsea","Mpumalanga","Vietnam"),
  ("Ap #797-1456 Orci. Avenue","Pietermaritzburg","Yukon","Norway"),
  ("6640 Ante, St.","Pasir Ris","Rogaland","Indonesia"),
  ("Ap #845-796 Blandit Avenue","Timaru","Troms og Finnmark","India");
INSERT INTO `direccion` (`direccion`,`ciudad`,`provincia`,`pais`)
VALUES
  ("P.O. Box 685, 3036 Donec Street","Bima","South Chungcheong","Ukraine"),
  ("P.O. Box 162, 2933 Lorem Rd.","Bến Tre","Imo","Sweden"),
  ("Ap #637-4898 Ultrices Road","Jambi","Northern Territory","Austria"),
  ("130-341 Tortor, Rd.","Dublin","Xīběi","Indonesia"),
  ("P.O. Box 752, 2349 Cras Road","Ensenada","South Australia","Pakistan"),
  ("573-9149 Arcu. Ave","Mapiripana","Bremen","Germany"),
  ("P.O. Box 599, 8327 Imperdiet, St.","Casole d'Elsa","Heredia","United Kingdom"),
  ("439-428 Ipsum. Avenue","Vernon","Coquimbo","Nigeria"),
  ("Ap #950-7041 Lorem St.","Jennersdorf","North Region","Netherlands"),
  ("Ap #455-3475 Varius St.","Tagbilaran","Sląskie","Indonesia"),
  ("Ap #673-2604 Risus, Street","Taguig","Nizhny Novgorod Oblast","Netherlands"),
  ("500-9913 Placerat Road","Dutse","Piura","Nigeria"),
  ("145-4844 Aliquam Rd.","Pamplona","Vichada","Peru"),
  ("7093 Eu Av.","Åkrehamn","North Island","Brazil"),
  ("Ap #330-2515 Ante Ave","Sincelejo","North Jeolla","New Zealand"),
  ("4135 Magna. St.","Tibet","Västra Götalands län","India"),
  ("P.O. Box 893, 4880 Fusce Avenue","Cajamarca","Lima","Costa Rica"),
  ("Ap #325-9720 Penatibus Rd.","Contagem","Gävleborgs län","Netherlands"),
  ("Ap #546-9548 Turpis. St.","Assen","Western Cape","Mexico"),
  ("P.O. Box 189, 3674 Ante Rd.","Orizaba","Hải Phòng","Belgium"),
  ("Ap #730-4423 Aliquam Street","Greymouth","Dnipropetrovsk oblast","Ukraine"),
  ("Ap #405-651 Cras Rd.","Lidingo","Antwerpen","Sweden"),
  ("P.O. Box 726, 6782 Per Ave","Cañas","Xīběi","Chile"),
  ("P.O. Box 847, 7442 Aliquet St.","Market Drayton","South Sumatra","Austria"),
  ("466-9404 Convallis, Av.","Purnea","Poitou-Charentes","Germany"),
  ("Ap #436-3264 Varius. Rd.","Tapachula","North Region","Netherlands"),
  ("Ap #859-4395 Sed Av.","Bahawalnagar","Zeeland","Ukraine"),
  ("P.O. Box 494, 505 Ornare, Rd.","Nam Sách","Aragón","Belgium"),
  ("413-4460 Aenean St.","Zaria","Alajuela","Chile"),
  ("3735 Enim. Road","Lebowakgomo","Balochistan","India"),
  ("1098 Purus St.","Itapipoca","Gävleborgs län","New Zealand"),
  ("P.O. Box 504, 5374 Scelerisque Street","Olsztyn","Leinster","Indonesia"),
  ("P.O. Box 507, 1649 Vel, Rd.","Pamplona","Bihar","Singapore"),
  ("Ap #222-5453 Rhoncus. St.","King William's Town","Hậu Giang","Turkey"),
  ("P.O. Box 652, 4561 Cursus Av.","Nässjö","Central Region","Germany"),
  ("P.O. Box 877, 7872 Ipsum Av.","Cabadbaran","Western Cape","Turkey"),
  ("2502 Vestibulum Rd.","Nelspruit","Niedersachsen","Norway"),
  ("Ap #347-3714 Proin Road","Matlock","Atacama","Ireland"),
  ("241-7430 Mi. Rd.","Grand-Leez","Free State","Sweden"),
  ("P.O. Box 324, 8322 Nulla Avenue","Lagos","Comunitat Valenciana","United States"),
  ("Ap #721-9255 Dolor St.","Pervomaisk","Khyber Pakhtoonkhwa","Chile"),
  ("P.O. Box 319, 5978 Phasellus Rd.","Mersin","Kaluga Oblast","Canada"),
  ("251-1463 Orci Avenue","Kharkiv","Sonora","Nigeria"),
  ("453-3991 Et Rd.","Wonju","Yucatán","Russian Federation"),
  ("Ap #220-9766 Dictum St.","Neunkirchen","Gauteng","United States"),
  ("Ap #576-9867 Sit St.","Maubeuge","Coquimbo","Russian Federation"),
  ("Ap #645-4702 Pretium Ave","Pasir Ris","Puebla","New Zealand"),
  ("Ap #965-5299 Ultrices Street","Bollnäs","West Region","Vietnam"),
  ("777-1635 Ac, Rd.","Ternate","O'Higgins","Philippines"),
  ("Ap #890-5279 Lacinia St.","Saint Petersburg","North Gyeongsang","Australia");
INSERT INTO `direccion` (`direccion`,`ciudad`,`provincia`,`pais`)
VALUES
  ("Ap #349-5822 Vitae Av.","Mascalucia","Tasmania","Norway"),
  ("Ap #459-1334 Praesent Avenue","Kargopol","Ceuta","Peru"),
  ("891-3962 Duis Street","Pembroke","Kogi","Chile"),
  ("785-9109 Amet, Ave","Bengkulu","Umbria","South Korea"),
  ("325-9513 Luctus St.","Dörtyol","North Region","China"),
  ("P.O. Box 250, 9131 Libero. St.","Dilsen-Stokkem","North Gyeongsang","South Africa"),
  ("645 Pede. Road","Uzhhorod","Małopolskie","Brazil"),
  ("511-3433 Eleifend St.","Daman","Junín","Turkey"),
  ("Ap #501-8061 Dolor St.","Matamoros","Jalisco","Spain"),
  ("Ap #508-4719 Dolor. Rd.","Caldera","Dorset","Netherlands"),
  ("Ap #866-9935 Blandit Rd.","Cork","Oryol Oblast","United States"),
  ("979-8359 Vel, Street","Kędzierzyn-Koźle","Eastern Visayas","Netherlands"),
  ("Ap #433-6185 Inceptos Rd.","Temuka","Nariño","Poland"),
  ("Ap #528-1589 Ut, St.","Kuruman","Dolnośląskie","Colombia"),
  ("957-6709 Duis Rd.","Invergordon","South Gyeongsang","Vietnam"),
  ("Ap #608-4433 Laoreet, Avenue","Belfast","Gelderland","Nigeria"),
  ("P.O. Box 324, 2851 Augue Av.","Tagum","Gävleborgs län","Singapore"),
  ("167-7039 Aenean Ave","Madrid","Los Ríos","Austria"),
  ("102-8017 Fringilla Street","Söderhamn","Donetsk oblast","Indonesia"),
  ("934-4039 Lobortis St.","Khushab","Atlántico","Colombia"),
  ("P.O. Box 325, 898 Aliquam St.","Kropyvnytskyi","Azad Kashmir","Australia"),
  ("Ap #116-216 Lorem, St.","Dannevirke","West Region","Philippines"),
  ("368-1627 Dui. Avenue","Daegu","Montana","Pakistan"),
  ("P.O. Box 868, 8781 Pede, St.","Basingstoke","Papua","South Korea"),
  ("P.O. Box 498, 1348 Odio, Road","Almere","Sumy oblast","Costa Rica"),
  ("964-6695 Vestibulum Rd.","Zirl","Xīběi","Nigeria"),
  ("424-1535 Maecenas Road","Worms","Bedfordshire","Norway"),
  ("P.O. Box 468, 9636 Donec St.","Ceuta","La Libertad","Ireland"),
  ("899-6061 Risus. Av.","Finspång","Borno","Chile"),
  ("Ap #519-3811 Ut Road","Rancagua","Xīnán","Netherlands"),
  ("912-4896 Ut Av.","Barddhaman","Trøndelag","Spain"),
  ("Ap #555-607 Lacus. Avenue","Neerglabbeek","Nghệ An","Netherlands"),
  ("Ap #283-3406 Sed Avenue","Tournefeuille","Lima","Philippines"),
  ("611-8233 Ut Road","Kharmang","Vlaams-Brabant","Netherlands"),
  ("6136 Nascetur Road","Haverfordwest","North West","Singapore"),
  ("P.O. Box 181, 9693 Tristique Rd.","Dunedin","Uttar Pradesh","Nigeria"),
  ("180-9087 Id Rd.","Dipolog","New South Wales","Austria"),
  ("654-7205 Neque Road","Sosnowiec","Kahramanmaraş","Canada"),
  ("P.O. Box 237, 6788 Suspendisse St.","Częstochowa","Salzburg","Spain"),
  ("8614 Malesuada Rd.","Poltava","Tasmania","Ireland"),
  ("512-9131 Donec Ave","Emalahleni","North Island","Austria"),
  ("Ap #735-3952 Nullam St.","Iquitos","Morelos","Italy"),
  ("818-3845 Nisi Road","Farsund","South Island","New Zealand"),
  ("Ap #425-1920 Nibh. Ave","Gangtok","Arunachal Pradesh","Chile"),
  ("Ap #905-6751 Varius. St.","Matamata","Jalisco","Indonesia"),
  ("Ap #559-3363 Pharetra Street","Villahermosa","Xīnán","South Korea"),
  ("Ap #274-356 Lacinia Rd.","Dublin","Ulyanovsk Oblast","Poland"),
  ("3543 Eleifend Rd.","Kristiansand","North-East Region","Singapore"),
  ("Ap #910-3824 Tincidunt St.","Burnie","Brussels Hoofdstedelijk Gewest","Turkey"),
  ("4878 Mauris St.","Juliaca","Yucatán","Colombia");
INSERT INTO `direccion` (`direccion`,`ciudad`,`provincia`,`pais`)
VALUES
  ("212-2170 Dignissim Ave","Palembang","Michigan","Sweden"),
  ("P.O. Box 179, 3294 Elit Rd.","Emalahleni","Huáběi","Mexico"),
  ("P.O. Box 587, 6525 Sit Ave","Sevastopol","Bangsamoro","United States"),
  ("9391 Euismod Road","Pforzheim","Nova Scotia","South Africa"),
  ("2562 Nulla. Av.","Oslo","Sutherland","Vietnam"),
  ("668 Mauris St.","Warren","British Columbia","Norway"),
  ("843-1519 Vulputate Ave","Mukachevo","National Capital Region","New Zealand"),
  ("697-9706 Molestie Ave","Canberra","Special Capital Region of Jakarta","United States"),
  ("Ap #305-5692 Egestas. Av.","Nizhyn","Kahramanmaraş","Costa Rica"),
  ("Ap #974-2511 Nisi. Rd.","Emalahleni","Schleswig-Holstein","Chile"),
  ("Ap #190-1879 Non Rd.","Des Moines","Boyacá","South Africa"),
  ("8928 Nulla. Street","Tczew","Cartago","Germany"),
  ("289-7714 Torquent St.","Khmilnyk","Balochistan","Belgium"),
  ("P.O. Box 481, 862 Luctus Rd.","Dutse","Flevoland","United Kingdom"),
  ("Ap #340-6383 Fusce St.","Chuncheon","Los Ríos","Belgium"),
  ("Ap #942-7249 Consequat St.","Calapan","Burgenland","Belgium"),
  ("519 Mi Av.","Oleksandriia","East Region","Netherlands"),
  ("Ap #535-8556 Ut Av.","Wazirabad","Noord Holland","United States"),
  ("479-280 Orci, St.","Uyo","Merionethshire","Peru"),
  ("Ap #684-8559 Risus Rd.","Padang","Gilgit Baltistan","Spain"),
  ("Ap #898-1760 Donec Av.","Patos","Himachal Pradesh","Ireland"),
  ("322-6130 Enim, Ave","Los Mochis","Mpumalanga","Mexico"),
  ("P.O. Box 295, 2627 Vestibulum Rd.","Montreal","Northern Mindanao","Austria"),
  ("Ap #108-6375 A Road","Kuruman","South Island","Costa Rica"),
  ("9389 Cras Avenue","Cork","North Jeolla","France"),
  ("552-2884 Diam Street","Bischofshofen","Kherson oblast","Australia"),
  ("Ap #322-7554 Magna. Street","Mo i Rana","Diyarbakır","Austria"),
  ("8460 Sapien St.","Khmelnytskyi","Cajamarca","France"),
  ("Ap #161-9717 Ultrices St.","Queilén","Berlin","Italy"),
  ("P.O. Box 717, 7689 Nec, St.","Villahermosa","Querétaro","China"),
  ("102-9668 Proin Avenue","Melle","San José","Poland"),
  ("815-8756 Mauris. Rd.","Haren","Lạng Sơn","Costa Rica"),
  ("2502 Mauris St.","Hafizabad","Sindh","Spain"),
  ("892-9181 Sit Road","Vereeniging","Nordland","Canada"),
  ("975-901 A, St.","Amsterdam","North West","Turkey"),
  ("Ap #981-284 Posuere St.","Molde","Bryansk Oblast","Ireland"),
  ("842-2113 Faucibus St.","Istanbul","Stockholms län","Sweden"),
  ("Ap #850-3218 Pede Road","Bukit Timah","Anambra","Netherlands"),
  ("904-7505 Lectus Av.","Galway","Morayshire","Nigeria"),
  ("Ap #821-5034 Neque Road","Baracaldo","Piemonte","New Zealand"),
  ("407 Iaculis, Street","Rueil-Malmaison","Balıkesir","Philippines"),
  ("8654 Sociis Avenue","Bajaur Agency","Vlaams-Brabant","Poland"),
  ("Ap #574-1195 Nunc Avenue","Ashburton","West Kalimantan","Vietnam"),
  ("P.O. Box 971, 430 Non Street","Kavaratti","Basilicata","Singapore"),
  ("3177 Non Rd.","Nizhny","Valle d'Aosta","Germany"),
  ("Ap #841-4655 Sapien Road","Velsk","Alajuela","Australia"),
  ("P.O. Box 397, 2207 Quisque Ave","Osogbo","Vienna","Netherlands"),
  ("Ap #146-5469 Tempor Rd.","La Plata","Dōngběi","Costa Rica"),
  ("473-5529 Tellus Rd.","Autelbas","Cartago","Belgium"),
  ("657-2445 Ac Road","Okene","Punjab","Pakistan");
INSERT INTO `direccion` (`direccion`,`ciudad`,`provincia`,`pais`)
VALUES
  ("P.O. Box 383, 7436 Odio. St.","Auckland","Swiętokrzyskie","Ireland"),
  ("115-3300 Bibendum Street","Daly","Chhattisgarh","United States"),
  ("469-7634 Duis Rd.","Paraíso","Munster","Singapore"),
  ("P.O. Box 294, 191 Morbi Road","Armidale","Special Capital Region of Jakarta","France"),
  ("550-8248 In Avenue","King William's Town","Puebla","Belgium"),
  ("Ap #324-6752 Vivamus Ave","Cartagena del Chairá","Troms og Finnmark","Turkey"),
  ("Ap #571-620 A, Rd.","Arica","São Paulo","Costa Rica"),
  ("P.O. Box 940, 3844 Mauris St.","Serang","West Nusa Tenggara","Austria"),
  ("397-8093 Magna Ave","Pangkalpinang","Guanacaste","South Africa"),
  ("5239 Nam Rd.","Hinckley","Araucanía","Belgium"),
  ("Ap #758-6742 Dui St.","Armadale","Coquimbo","Turkey"),
  ("P.O. Box 813, 8665 Vulputate Rd.","Leticia","East Region","Canada"),
  ("P.O. Box 866, 8310 Fringilla St.","Suwon","Antwerpen","South Korea"),
  ("Ap #759-8517 Sagittis St.","Barra do Corda","Östergötlands län","Philippines"),
  ("4778 Arcu. Avenue","Çarşamba","Poltava oblast","New Zealand"),
  ("552-4593 Nulla. Road","Barra do Corda","Xīnán","Indonesia"),
  ("1944 Nec St.","Puntarenas","Adana","Belgium"),
  ("Ap #905-3785 Nullam Rd.","Kano","Xīběi","Turkey"),
  ("526-9977 Velit Street","Phong Thổ","South Gyeongsang","United Kingdom"),
  ("P.O. Box 171, 9295 Maecenas St.","Zaporizhzhia","Huáběi","India"),
  ("Ap #738-1027 Ultricies Avenue","Lerum","Poitou-Charentes","Italy"),
  ("1125 Lectus St.","Palembang","Metropolitana de Santiago","South Korea"),
  ("P.O. Box 266, 7096 Cras St.","Ödemiş","Sachsen","Germany"),
  ("377-1581 Sapien, Rd.","Salerno","North West","Poland"),
  ("Ap #836-7011 Elit, St.","Pamplona","FATA","Nigeria"),
  ("P.O. Box 486, 5035 Sit Rd.","Vienna","Leinster","Nigeria"),
  ("1771 Laoreet Ave","Olmen","Bình Dương","South Korea"),
  ("Ap #139-1862 Eget St.","Korba","Massachusetts","Italy"),
  ("754-614 Ad Rd.","Silvassa","La Rioja","Peru"),
  ("325-7714 Feugiat Ave","Hattersheim am Main","Valparaíso","India"),
  ("836-9682 Magna. Street","Cereté","Oaxaca","Germany"),
  ("Ap #858-528 Sapien Ave","Rạch Giá","Namen","Poland"),
  ("326-9778 Ligula. Rd.","Huancayo","Oaxaca","Poland"),
  ("Ap #821-171 Turpis Rd.","Agustín Codazzi","Bremen","Brazil"),
  ("Ap #269-5995 Mattis. Ave","Sujawal","North Region","India"),
  ("P.O. Box 767, 1352 Dolor Road","Seongnam","Kocaeli","Peru"),
  ("145-3664 Nec Rd.","Bida","Oost-Vlaanderen","India"),
  ("P.O. Box 249, 879 Et Road","Kurram Agency","South Australia","Sweden"),
  ("616-9053 Per Street","Aurillac","Heredia","South Korea"),
  ("259-9939 Dui Rd.","Tunja","Dadra and Nagar Haveli","Sweden"),
  ("891-7144 Vivamus Avenue","Doñihue","Loreto","Colombia"),
  ("Ap #569-9574 Magnis St.","Angers","Tiền Giang","Indonesia"),
  ("Ap #831-235 Aliquet, St.","Bama","North West","Chile"),
  ("8612 Libero Av.","Southern Islands","Upper Austria","Russian Federation"),
  ("9023 Nec Avenue","Adana","Vlaams-Brabant","Poland"),
  ("Ap #347-8035 Iaculis, Avenue","Kaduna","Risaralda","Canada"),
  ("Ap #991-3132 Nunc Ave","Sellano","Jeju","Peru"),
  ("Ap #633-7902 Dis St.","Puntarenas","Berlin","Pakistan"),
  ("Ap #800-9304 Fermentum St.","Zielona Góra","Guanacaste","Austria"),
  ("996-8479 Donec Rd.","Thabazimbi","Bắc Giang","Ukraine");
INSERT INTO `direccion` (`direccion`,`ciudad`,`provincia`,`pais`)
VALUES
  ("Ap #791-9070 Et St.","Putignano","Puno","Mexico"),
  ("610-8136 Eu St.","Palmerston","Xīběi","Colombia"),
  ("7180 Eu, Av.","Caen","Piura","Belgium"),
  ("536-1989 Duis St.","Sapele","Araucanía","Spain"),
  ("5783 Ligula Street","Paradise","Oaxaca","Mexico"),
  ("Ap #412-4656 Non St.","Phuthaditjhaba","Bahia","United States"),
  ("Ap #526-1742 Ut Ave","Iqaluit","Podkarpackie","Ukraine"),
  ("Ap #975-1682 Et, Rd.","Samarinda","Eastern Visayas","Pakistan"),
  ("Ap #114-6522 Fusce Avenue","Charters Towers","Sindh","Turkey"),
  ("4638 Dictum Rd.","Zhytomyr","Quảng Nam","United Kingdom"),
  ("7481 Semper Rd.","Gunsan","North Maluku","Canada"),
  ("P.O. Box 341, 2698 Turpis. Road","Ibagué","Bình Định","United Kingdom"),
  ("Ap #639-4976 Sit Street","Fundación","Australian Capital Territory","France"),
  ("5665 In Avenue","Belfast","West Region","Pakistan"),
  ("226-8296 Sed, Road","Stalowa Wola","FATA","South Africa"),
  ("505-2133 Ipsum Rd.","Đồng Xoài","Dalarnas län","South Korea"),
  ("1794 Mus. Road","Oamaru","Lambayeque","Singapore"),
  ("Ap #935-7892 Commodo Street","Ikot Ekpene","Munster","United States"),
  ("322-2516 Aliquet, Av.","Kursk","Bicol Region","South Africa"),
  ("Ap #342-9483 Lectus. Street","Kursk","Cantabria","Poland"),
  ("P.O. Box 445, 7866 Rutrum Rd.","Irkutsk","Illinois","South Korea"),
  ("Ap #867-5042 Luctus, Rd.","Nanterre","Gelderland","Singapore"),
  ("228-4436 Et, Rd.","Orenburg","Southeast Sulawesi","Australia"),
  ("241-309 Mauris St.","Clementi","Vichada","Turkey"),
  ("Ap #857-1060 Ullamcorper, Av.","San Francisco","Lower Austria","Australia"),
  ("P.O. Box 867, 2511 Ultrices, Ave","Valladolid","Morelos","Brazil"),
  ("9085 Donec Road","Daejeon","Viken","France"),
  ("150-7300 Amet Road","Xinjiang","New South Wales","Costa Rica"),
  ("603-6784 Sapien. Road","Pyeongtaek","Northern Cape","Germany"),
  ("Ap #187-5840 Tempus Av.","Levallois-Perret","Haryana","Sweden"),
  ("P.O. Box 654, 7539 Tristique Road","VTM","Rheinland-Pfalz","Poland"),
  ("216-1810 Nascetur St.","İslahiye","Mecklenburg-Vorpommern","Brazil"),
  ("301-1649 Primis Road","Port Augusta","Stockholms län","Vietnam"),
  ("477-9156 Dictum Ave","Sandviken","Luik","Mexico"),
  ("P.O. Box 211, 4413 Suspendisse Av.","Curacaví","Huádōng","Spain"),
  ("Ap #520-8552 Scelerisque Rd.","Kungälv","Clackmannanshire","South Korea"),
  ("151-6949 Et Road","Chernihiv","Sokoto","New Zealand"),
  ("390-658 Sed Rd.","Boryeong","Gelderland","Australia"),
  ("532-9177 Luctus Ave","Whitehorse","Banten","Italy"),
  ("992-6554 Vulputate, St.","Iquique","Distrito Capital","Peru"),
  ("463-7051 Eu St.","Samaniego","Đồng Tháp","Ukraine"),
  ("Ap #316-7475 Arcu. Street","Gold Coast","Los Ríos","Ireland"),
  ("Ap #448-9225 Id Rd.","Vị Thanh","Cesar","Peru"),
  ("Ap #147-7196 Metus Road","Gatchina","Munster","Costa Rica"),
  ("P.O. Box 998, 786 Dictum Ave","Casciana Terme","New South Wales","Vietnam"),
  ("Ap #356-1564 Neque Avenue","Matera","Cherkasy oblast","Italy"),
  ("657-3718 Lorem, Ave","Niterói","Rutland","Vietnam"),
  ("6144 Semper Road","Ambon","Provence-Alpes-Côte d'Azur","Mexico"),
  ("659-918 Parturient Ave","Quảng Ngãi","Luhansk oblast","Chile"),
  ("190-553 Proin Rd.","Ramsel","Sevastopol City","Ukraine");
INSERT INTO `direccion` (`direccion`,`ciudad`,`provincia`,`pais`)
VALUES
  ("Ap #953-9122 Egestas Rd.","Westport","Kerala","France"),
  ("8612 Torquent Av.","Scarborough","Chernivtsi oblast","South Africa"),
  ("684-1027 Ipsum Rd.","Siedlce","South Chungcheong","Pakistan"),
  ("724-7751 Orci Street","Sogamoso","South Kalimantan","Austria"),
  ("P.O. Box 896, 4166 Sed Av.","Kaduna","Veneto","India"),
  ("429-4526 Tristique Rd.","Belford Roxo","Ancash","South Africa"),
  ("609-6940 Ante Street","Serangoon","Trentino-Alto Adige","Germany"),
  ("P.O. Box 895, 5676 Aliquam Ave","Cork","Sindh","Ireland"),
  ("P.O. Box 811, 7528 Volutpat. Road","Helensburgh","Rivne oblast","Colombia"),
  ("Ap #959-8315 Sagittis Ave","Dublin","Oyo","Austria"),
  ("Ap #800-3101 Erat Road","Manila","British Columbia","Canada"),
  ("5361 Et Street","Pomarico","Western Cape","Australia"),
  ("849-6670 Donec St.","Pachuca","Zhōngnán","South Korea"),
  ("Ap #306-6110 Amet Rd.","Osasco","Puno","Sweden"),
  ("Ap #685-2002 Dolor Rd.","Omaha","Puntarenas","Turkey"),
  ("P.O. Box 861, 7440 Hendrerit Avenue","Nowshera","Gävleborgs län","South Korea"),
  ("Ap #284-5264 Odio. Rd.","La Unión","Khyber Pakhtoonkhwa","Costa Rica"),
  ("Ap #348-5494 Dolor. Road","Cuernavaca","East Region","Nigeria"),
  ("4115 Non Street","Kremenchuk","Carinthia","Australia"),
  ("Ap #687-7630 Euismod Rd.","Bạc Liêu","KwaZulu-Natal","Canada"),
  ("9290 Blandit Ave","Yurimaguas","Huádōng","United States"),
  ("Ap #116-9345 Magna St.","São José dos Pinhais","Coquimbo","Mexico"),
  ("9510 Elit, St.","Biên Hòa","Andhra Pradesh","France"),
  ("P.O. Box 111, 885 Diam. Rd.","Lexington","North-East Region","Netherlands"),
  ("P.O. Box 656, 8379 Elementum Rd.","Pereto","Risaralda","United States"),
  ("8621 Nulla Avenue","Soledad","Rivers","Australia"),
  ("657-4556 Quisque Avenue","Milwaukee","Riau","Pakistan"),
  ("Ap #110-9413 Ipsum St.","Cajamarca","Borno","Singapore"),
  ("240-4625 Dui. Rd.","Sullana","Aragón","Indonesia"),
  ("Ap #352-654 Ipsum. St.","Norfolk","Abruzzo","Philippines"),
  ("654-2104 Sed Av.","Saltillo","Daman and Diu","United Kingdom"),
  ("Ap #876-5225 Suspendisse St.","Liaoning","Manitoba","Italy"),
  ("165-1061 Vitae Road","South Jakarta","South Chungcheong","China"),
  ("P.O. Box 128, 239 Velit St.","Sant'Ilario dello Ionio","Podkarpackie","Chile"),
  ("955-4321 Vulputate, Road","Saint-Servais","North Sulawesi","Nigeria"),
  ("845-2635 Facilisis, Ave","Hilversum","Rio de Janeiro","Nigeria"),
  ("1177 Suspendisse Rd.","Jeju","Australian Capital Territory","United States"),
  ("619-7234 Sed Rd.","Astore","Limpopo","Chile"),
  ("843-5467 Integer Road","Hawick","Picardie","Ukraine"),
  ("Ap #102-3187 Sem Rd.","Taupo","Mississippi","Sweden"),
  ("Ap #211-8234 Posuere, Rd.","Bagh","Alajuela","Canada"),
  ("964-4550 Ante Ave","Seogwipo","Saratov Oblast","Costa Rica"),
  ("Ap #536-724 Convallis Rd.","Gaithersburg","Aquitaine","United Kingdom"),
  ("Ap #438-3051 Pellentesque St.","Pinetown","Xīnán","Costa Rica"),
  ("Ap #740-9023 Ultrices Av.","Ajaccio","Atacama","Vietnam"),
  ("138-6412 Ullamcorper St.","Arauca","North Island","Ireland"),
  ("7144 Sit St.","Wekweti","Metropolitana de Santiago","Australia"),
  ("219-7398 Non Rd.","Leirvik","Upper Austria","South Korea"),
  ("Ap #605-6350 Id St.","Gillette","Maranhão","Indonesia"),
  ("713-9936 Purus Rd.","Amersfoort","Campania","Peru");