# Generated by Django 4.1 on 2022-08-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
            ],
            options={
                'db_table': 'user_cliente',
                'managed': False,
            },
        ),
    ]
