# Generated by Django 4.0.6 on 2022-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField()),
                ('CVV', models.TextField()),
                ('fecha_otorgamiento', models.TextField()),
                ('fecha_expiracion', models.TextField()),
                ('tipo_tarjeta_id', models.IntegerField()),
                ('marca_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
