# Generated by Django 4.1 on 2022-08-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': True},
        ),
    ]
