# Generated by Django 4.1 on 2022-08-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_alter_tarjeta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': False},
        ),
    ]
