# Generated by Django 4.1 on 2022-08-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_id", models.IntegerField()),
                ("balance", models.IntegerField()),
                ("iban", models.TextField()),
            ],
            options={
                "db_table": "cuenta",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                ("loan_type", models.TextField()),
                ("loan_date", models.TextField()),
                ("loan_total", models.IntegerField()),
                ("customer_id", models.IntegerField()),
            ],
            options={
                "db_table": "prestamo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoCuentas",
            fields=[
                ("cuenta_id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_cuenta", models.TextField()),
            ],
            options={
                "db_table": "tipo_cuentas",
                "managed": False,
            },
        ),
    ]
