# Generated by Django 4.1 on 2022-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_cuenta_prestamo_tipocuentas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.TextField()),
                ('numero', models.TextField()),
                ('ciudad', models.TextField()),
                ('provincia', models.TextField()),
                ('pais', models.TextField()),
                ('customer_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
    ]
